name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Branch abhängig ausgeben
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "Hello, world! Du hast auf den Main-Branch gepusht."
          else
            echo "Hello, world! Du hast auf den Branch ${{ github.ref_name }} gepusht."
          fi

      - name: Run a multi-line script
        run: |
          echo "Aloha"
          echo "This is a multi-line script"
